#!/bin/sh -x

init=/sbin/init

ANDROID_IMG=""
android_update()
{
    echo "android_update"
    
    # New partions
    fdisk /dev/mmcblk0 < /etc/fdisk-u-android.input
    /bin/unzip -o -P Mx*98Ndqx01@Jc $ANDROID_IMG mke2fs -d /tmp/
    chmod a+x /tmp/mke2fs

    # format sdcard
    /bin/unzip -l $ANDROID_IMG | grep mkdosfs
    if [ $? -eq "0" ]; then
    /bin/unzip -o -P Mx*98Ndqx01@Jc $ANDROID_IMG mkdosfs -d /tmp/
    chmod a+x /tmp/mkdosfs
    mount -t vfat /dev/mmcblk0p1 /newroot
        if [ $? -ne "0" ]; then
            /tmp/mkdosfs -v -F 32 -n media /dev/mmcblk0p1
        else
            umount /newroot
        fi
    fi

    # Update bootloader
    /bin/unzip -l $ANDROID_IMG | grep u-boot.bin
    if [ $? -eq "0" ]; then
        echo 1 > /sys/devices/platform/mxsdhci.2/mmc_host/mmc0/mmc0:0001/boot_config
        /bin/unzip -o -p -P Mx*98Ndqx01@Jc $ANDROID_IMG u-boot.bin | dd of=/dev/mmcblk0 skip=2 seek=2
        echo 8 > /sys/devices/platform/mxsdhci.2/mmc_host/mmc0/mmc0:0001/boot_config
        echo 2 > /sys/devices/platform/mxsdhci.2/mmc_host/mmc0/mmc0:0001/boot_bus_config
    fi

    # Update initramfs
    /bin/unzip -l $ANDROID_IMG | grep uImage-initramfs
    if [ $? -eq "0" ]; then
        /bin/unzip -o -p -P Mx*98Ndqx01@Jc $ANDROID_IMG uImage-initramfs | dd of=/dev/mmcblk0 bs=512 seek=20480
    fi


    # Update boot splash
    /bin/unzip -l $ANDROID_IMG | grep boot-splash
    if [ $? -eq "0" ]; then
       /bin/unzip -o -p -P Mx*98Ndqx01@Jc $ANDROID_IMG boot-splash | dd of=/dev/mmcblk0 bs=512 seek=2048
    fi

    # Update waveform data
    /bin/unzip -l $ANDROID_IMG | grep epdc_E97_V220.fw
    if [ $? -eq "0" ]; then
       /bin/unzip -o -p -P Mx*98Ndqx01@Jc $ANDROID_IMG epdc_E97_V220.fw | dd of=/dev/mmcblk0 bs=512 seek=4096
    fi

    # Update uImage
    /bin/unzip -l $ANDROID_IMG | grep uImage
    if [ $? -eq "0" ]; then
       /bin/unzip -o -p -P Mx*98Ndqx01@Jc $ANDROID_IMG uImage | dd of=/dev/mmcblk0 bs=512 seek=8192
    fi

    # Update uramdisk.img
    /bin/unzip -l $ANDROID_IMG | grep uramdisk.img
    if [ $? -eq "0" ]; then
       /bin/unzip -o -p -P Mx*98Ndqx01@Jc $ANDROID_IMG uramdisk.img | dd of=/dev/mmcblk0 bs=512 seek=14336
    fi

    # Update system.img
    /bin/unzip -l $ANDROID_IMG | grep system.img
    if [ $? -eq "0" ]; then
        /tmp/mke2fs /dev/mmcblk0p2 -O ^extent -L system
        /bin/unzip -o -p -P Mx*98Ndqx01@Jc $ANDROID_IMG system.img | dd of=/dev/mmcblk0p2
    fi

    # Update data.img
    /tmp/mke2fs /dev/mmcblk0p5 -O ^extent -L data
    /bin/unzip -l $ANDROID_IMG | grep userdata.img
    if [ $? -eq "0" ]; then
        /bin/unzip -o -p -P Mx*98Ndqx01@Jc $ANDROID_IMG userdata.img | dd of=/dev/mmcblk0p5
    fi

    /tmp/mke2fs /dev/mmcblk0p6 -O ^extent -L cache
}

check_update()
{
  update_pkg=""

  for i in $(ls /mnt/mmc|grep "update-[0-9]\{8\}.zip")
  do
	  continue
  done

  echo $i
  ANDROID_IMG=/mnt/mmc/$i

  if [ ! -z $i ]; then
    /bin/unzip -l $ANDROID_IMG | grep system*.img
    RET=$?
    if [ $RET == 0 ]; then
        android_update
        sync
        reboot
        sleep 8
#      poweroff
#      exit
#      sleep 10000
    fi
  fi

  for i in $(ls /mnt/mmc|grep "update-[0-9]\{8\}.zip")
  do
	  continue
  done

  echo $i

  if [ ! -z $i ]; then
    # Extracting files.
    fdisk /dev/mmcblk0 < /etc/fdisk-u-boox.input

    echo "Extracting files..."
    
    update_pkg=/mnt/mmc/$i

    mxcfb_disp_msg /bin/extracting.dat

    mkdir -p /mnt/rootfs

    mount -t ext4 /dev/mmcblk0p1 /newroot
    if [ $? -eq "0" ]; then
        umount /newroot
    else
    /bin/unzip -o -P Mx*98Ndqx01@Jc $update_pkg boot/u-boot.bin -d /tmp/
    if [ -f "/tmp/boot/u-boot.bin" ]; then
        echo 1 > /sys/devices/platform/mxsdhci.2/mmc_host/mmc0/mmc0:0001/boot_config
        dd if=/tmp/boot/u-boot.bin of=/dev/mmcblk0 skip=2 seek=2
        echo 8 > /sys/devices/platform/mxsdhci.2/mmc_host/mmc0/mmc0:0001/boot_config
        echo 2 > /sys/devices/platform/mxsdhci.2/mmc_host/mmc0/mmc0:0001/boot_bus_config
    fi
    fi

    /bin/unzip -o -P Mx*98Ndqx01@Jc $update_pkg usr/bin/mke2fs -d /tmp/
    RET=$?
    if [ $RET == 0 ]; then
        chmod 777 /tmp/usr/bin/mke2fs
        /tmp/usr/bin/mke2fs -T ext4 -m0 /dev/mmcblk0p1
        mount -t ext4 /dev/mmcblk0p1 /mnt/rootfs
        cd /mnt/rootfs
    else
        mount -t ext4 /dev/mmcblk0p1 /mnt/rootfs
        cd /mnt/rootfs
        rm -rf *
    fi
    # Do update.
    mxcfb_disp_msg /bin/updating.dat

    # format sdcard
    /bin/unzip -o -P Mx*98Ndqx01@Jc $update_pkg usr/bin/mkdosfs -d /tmp/
    chmod a+x /tmp/usr/bin/mkdosfs
    mount -t vfat /dev/mmcblk0p3 /newroot
    if [ $? -eq "0" ]; then
        umount /newroot
    else
        /tmp/usr/bin/mkdosfs -v -F 32 -n boox /dev/mmcblk0p3
    fi

    mount -t ext4 /dev/mmcblk0p2 /newroot
    if [ $? -eq "0" ]; then
        umount /newroot
    else
        /tmp/usr/bin/mke2fs -T ext4 -m0 /dev/mmcblk0p2
    fi

    sync 
    # Decrypt & extract the update package
    /bin/unzip -P Mx*98Ndqx01@Jc $update_pkg -d /mnt/rootfs
    sync 
    sleep 4
    
    if [ -f "boot/post_update.sh" ]; then
        cp boot/post_update.sh /tmp
        rm boot/post_update.sh
    fi


    # Update boot splash
    if [ -f "boot/boot-splash" ]; then
       dd if=boot/boot-splash of=/dev/mmcblk0 bs=512 seek=2048
    fi

    # Update waveform data
    if [ -f "boot/epdc_*.fw" ]; then
       dd if=boot/epdc_*.fw of=/dev/mmcblk0 bs=512 seek=4096
    fi

    # Update uImage
    if [ -f "boot/uImage" ]; then
        dd if=boot/uImage of=/dev/mmcblk0 bs=512 seek=8192
    fi

    # Update initramfs
    if [ -f "boot/uImage-initramfs" ]; then
        dd if=boot/uImage-initramfs of=/dev/mmcblk0 bs=512 seek=12288
    fi

    # Copy custom fonts
    if [ -d "/mnt/mmc/fonts" ]; then
        cp  /mnt/mmc/fonts/*.ttf /mnt/rootfs/opt/onyx/arm/lib/fonts/
    fi

    #Delete the boot directory.
    rm -rf boot

    mknod dev/console  c 5 1
    mknod dev/null     c 1 3
    sync
 
	cd /
    umount /mnt/rootfs

    echo "Update complete."
    # Update complete, change display
    mxcfb_disp_msg /bin/booting.dat

    if [ -f "/tmp/post_update.sh" ]; then
        sh /tmp/post_update.sh
        rm /tmp/post_update.sh
    fi

    # Restart device
    reboot
  else
    echo "No update found."
    mxcfb_disp_msg /bin/no_updates.dat
  fi
}

normal_boot()
{
  # Mount real rootfs
  mount -t ext4 /dev/mmcblk0p1 /newroot

  # Check if there is a init script
  if [ -x "/newroot/${init}" ] ; then
    #Unmount all other mounts so that the ram used by
    #the initramfs can be cleared after switch_root
    umount /sys /proc

    #Switch to the new root and execute init
    exec switch_root /newroot "${init}"
  fi
}

# Mount things needed by this script
busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys

# Create all the symlinks to /bin/busybox
busybox --install -s

# Main entry for initramfs
echo "Entering initramfs... V1.1"

# Load code page modules.
insmod /lib/modules/nls_iso8859-1.ko
insmod /lib/modules/nls_cp437.ko

retry_count=0
while [ $retry_count -lt 5 ]
do
  if [ -b "/dev/mmcblk1p1" ]; then
    mount -t vfat /dev/mmcblk1p1 /mnt/mmc
    if [ $? = 0 ]; then
      break
    fi
  fi
  sleep 1
  retry_count=`expr $retry_count + 1`
done

if [ $retry_count -lt 5 ]; then
  check_update
  umount /mnt/mmc
fi

mount -t vfat /dev/mmcblk1 /mnt/mmc
if [ $? = 0 ]; then
  check_update
  umount /mnt/mmc
else
  # No sd card in slot
  echo "Mount SD card failed"
  mxcfb_disp_msg /bin/no_updates.dat
fi

# Start normal boot process.
normal_boot

# Impossible to reach.
exec sh
